import { UserDao } from "@daos";
import bcrypt from "bcrypt";
import { Request, Response, Router } from "express";
import {
  BAD_REQUEST,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
  OK,
  UNAUTHORIZED,
} from "http-status-codes";

import {
  jwtCookieProps,
  JwtService,
  logger,
  loginEmailNotVerifiedError,
  loginWrongEmailError,
  loginWrongPasswordError,
  paramMissingError,
  recoverPasswordWrongEmailError,
  userNotFoundError,
} from "@shared";

const router = Router();
const userDao = new UserDao();
const jwtService = new JwtService();

/**
 *
 * POST /api/auth/login : Login user.
 *
 * @body        of format: { email: string, password: string }
 *              where:
 *                email should be a valid email
 *                password should be at least 8 digits long
 *
 *
 * on success                     @return HTTP 200 & signed JWT cookie
 *                                         with an email payload
 *
 * on missing email or password   @return HTTP 400 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 * on email not registered        @return HTTP 401 & body of format:
 * on email not verified
 * on password being wrong
 *   {
 *     "error": "message"
 *   }
 *
 * on server failure              @return HTTP 500 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 */
router.post("/login", async (req: Request, res: Response) => {
  try {
    // Check email and password present
    const { email, password } = req.body;
    if (!(email && password)) {
      return res.status(BAD_REQUEST).json({
        error: paramMissingError,
      });
    }
    // Fetch user
    const user = await userDao.getOne(email);
    if (!user) {
      return res.status(UNAUTHORIZED).json({
        error: loginWrongEmailError,
      });
    }
    // Check email is verified
    if (!user.active) {
      return res.status(UNAUTHORIZED).json({
        error: loginEmailNotVerifiedError,
      });
    }
    // Check password
    const pwdPassed = await bcrypt.compare(password, user.pwdHash);
    if (!pwdPassed) {
      return res.status(UNAUTHORIZED).json({
        error: loginWrongPasswordError,
      });
    }
    // Setup Admin Cookie
    const jwt = await jwtService.getJwt({
      email: user.email,
    });
    const { key, options } = jwtCookieProps;
    res.cookie(key, jwt, options);
    // Set login time
    userDao.addLoginTime(email, new Date());

    return res.status(OK).end();
  } catch (err) {
    logger.error(err.message, err);

    return res.status(INTERNAL_SERVER_ERROR).json({
      error: err.message,
    });
  }
});

/**
 *
 * POST /api/auth/recover : Changes a user's pasword to a new randomly generated one
 *                            and sends an email with it.
 *
 * @body        of format: { email: string }
 *              where:
 *                email should be registered
 *
 *
 * on success                      @return HTTP 200
 *
 * on missing email                @return HTTP 400 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 * on email not registered         @return HTTP 409 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 * on server failure               @return HTTP 500 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 */
router.post("/recover", async (req: Request, res: Response) => {
  try {
    // Check email present
    const { email } = req.body;
    if (!email) {
      return res.status(BAD_REQUEST).json({
        error: paramMissingError,
      });
    } else if (!(await userDao.getOne(email))) {
      return res.status(CONFLICT).json({
        error: recoverPasswordWrongEmailError,
      });
    }
    // Generate new password
    const newPassword = userDao.createNewPassword(email);
    if (newPassword === null) {
      return res.status(CONFLICT).json({
        error: userNotFoundError,
      });
    }

    return res.status(OK).end();
  } catch (err) {
    logger.error(err.message, err);

    return res.status(INTERNAL_SERVER_ERROR).json({
      error: err.message,
    });
  }
});

/**
 *
 * POST /api/auth/validate : Validates an email.
 *
 * @body        of format: { hash: string }
 *              where:
 *                hash being hash generated by /api/users/add or
 *                  /api/users/register for a given email
 *
 *
 * on success                      @return HTTP 200
 *
 * on missing hash                 @return HTTP 400 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 * on server failure               @return HTTP 500 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 */
router.post("/validate", async (req: Request, res: Response) => {
  try {
    // Check hash is present
    const { hash } = req.body;
    if (!hash) {
      return res.status(BAD_REQUEST).json({
        error: paramMissingError,
      });
    }

    await userDao.validateEmail(hash);

    return res.status(OK).end();
  } catch (err) {
    logger.error(err.message, err);

    return res.status(INTERNAL_SERVER_ERROR).json({
      error: err.message,
    });
  }
});

/**
 *
 * GET /api/auth/logout : Logs out a user.
 *
 *
 * on success                      @return        HTTP 200
 *                                 @removeCookie  JwtTokenKey
 *
 * on server failure               @return        HTTP 500 & body of format:
 *   {
 *     "error": "message"
 *   }
 *
 */
router.get("/logout", async (req: Request, res: Response) => {
  try {
    const { key, options } = jwtCookieProps;
    res.clearCookie(key);

    return res.status(OK).end();
  } catch (err) {
    logger.error(err.message, err);

    return res.status(INTERNAL_SERVER_ERROR).json({
      error: err.message,
    });
  }
});

export default router;
